### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by neuralsys** [xafero/JNetCall#3]
Hi, can it be used with java lower then 18?

Thanks.

**Comment by xafero** [comment]
What do you want?
1. Java calling C#
2. C# calling Java

**Comment by neuralsys** [comment]
Java to C#

**Comment by xafero** [comment]
I pushed a Java 8 source backport into https://github.com/xafero/JNetCall/tree/old-java ...

**Comment by neuralsys** [comment]
I get this error.
Exception in thread "Thread-1" java.lang.NoSuchMethodError: java.nio.file.Path.of(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;
        at jnethotel.java.windows.WinVmRef.loadLib(WinVmRef.java:29)

**Comment by xafero** [comment]
That's due to my newer JDK compiler not telling me which methods are actually existing in this older version.

In this specific case, it is not Path.of, because that's only since Java 11, but instead it should be Paths.get

**Comment by xafero** [comment]
Now it works with Oracle Java 1.8.0_181 after some more back-porting.

**Comment by xafero** [comment]
If you need any help, please reopen. Otherwise, my backport stays in this mentioned branch.

**Comment by neuralsys** [comment]
Is it possible to return list of objects from C# to Java?

**Comment by xafero** [comment]
See https://github.com/xafero/JNetCall/blob/old-java/JVM/jnetcall-java-tests/src/test/java/jnetcall/java/tests/CallTest.java ...

If you transmit a list of objects, like "class Person(string name, int age)", it actually internally has to be converted into an object array of primitive values, like ( ("H",1), ("B",2) ). If you try to send something like this, look at those example test cases.

**Comment by neuralsys** [comment]
I'm getting this error

at jnetcall.java.client.ClrContainer.<init>(ClrContainer.java:23)
	at jnetcall.java.client.ClrTransport.lambda$new$0(ClrTransport.java:44)
	at jnetbase.java.threads.SingleThread.doMyLoop(SingleThread.java:53)
	at jnetbase.java.threads.SingleThread.doLoop(SingleThread.java:46)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.UnsupportedOperationException: hostfxr_initialize_for_runtime_config failed with: 1
	at jnethotel.java.interop.BaseCoreClr.get_load_assembly_and_get_function_pointer_fn(BaseCoreClr.java:41)
	at jnethotel.java.interop.BaseCoreClr.load_assembly_and_get_callback(BaseCoreClr.java:84)
	at jnethotel.java.Clr.getCallback(Clr.java:41)
	at jnetcall.java.client.ClrContainer.getCallCallback(ClrContainer.java:57)
	at jnetcall.java.client.ClrContainer.setupClr(ClrContainer.java:31)
	at jnetcall.java.client.ClrContainer.<init>(ClrContainer.java:19)

**Comment by xafero** [comment]
What do you expect me to do with this? Do you want me to fantasize about what code you might be running? Why did I even bother to provide a test program (alienator) and stuff? 

In Build.bat (https://github.com/xafero/JNetCall/blob/main/build.bat) you can see the following commands:
`java -jar alienator-java\target\alienator-java.jar`

If you can run my test program (a simple calculator example), then your code is to blame. 
But if not, maybe your .NET runtime can not be loaded or some other error I of course cannot read from your mind.

**Comment by neuralsys** [comment]
I'm sorry. I posted in a hurry without an explanation part.
I got it running.
Thanks
